print('You are now in a dungeon and depends on your options u might just barly survive')
print('=============================================================================')

game = input('Type yes to start the game: ')
print('')
print('a groupe of monsters are heading toward you and u have a few seconds to decide what to do, choose wisly! ')
print('')
print('there is a machien gun on your left rear, and a door that could be locked on ur right! ')
print('there also a mysterious treasure room behind u! ')
print('')
print('do u want to pick up the gun and kill the monsters, or run away through the door and lock it?')
print('there is also a thrid option wich is for')
machiengun = input(' type "gun" for gun and "door" for the door and "room" to go the mysteirous treasure room. ')
if machiengun == 'gun' :
    print('u have killed the monsters and pissed off their leader and now he is coming for u! ')
    print('')
    print('now that their leader is coming for u u have tow choices: ')
    print('1- run and hide ')
    print('2- reload your machiengun and fight their leader ')
    leader = input('Type "1" or "2" fill in ur answer befor their leader rip u apart :D ')
    if leader == '1' :
        print('you ran from their leader and hid behind the rock ')
        print('their leader found cuz u were afriad to attack and killed you ')
        print('monsters have won... ')
        print('You have Lost:) ')
        print('                 _.------.                        .----.__')
        print('           /         \_.       ._           /---.__  ')
        print('          |  O    O   |\\___  //|          /       `\ |' )
        print('          |  .vvvvv.  | )   `(/ |         | o     o  \|' )
        print('          /  |     |  |/      \ |  /|   ./| .vvvvv.  |' )


    else :  
        print('it was an intense fight and ur are bleeding, but u sucsessfully killed their leader and left the dungeon! ')
        print('congratulations u have WON! ')
        print('..... (¯`v´¯)♥')
        print('.......•.¸.•´')
        print('....¸.•´')
        print('...')
        print(' ☻/')
        print('/▌♥♥')
        print('/ \ ♥♥')
 
if machiengun =='door' :
    print('u ran away from the monsters, but now u cant go back from the same door cuz its locked! ')
    print('u have to fine another way out of this dungeon! ') 
    print('u have a split way ahead of you! it could lead to your death choose wisly ')
    door = input('Type in "right" to go right and "left" to go left: ')
   
    if door == 'right' :
        print('after u went right there is might be a trap so be carfull. ')
        print('')
        print('u have 2 options: ')
        print('1- run through the road so if there was a trap  wont get cought in it. ')
        print('2- walk carfully but then the trap might be fast and kill you befor u can even react. ')
        print('')
        trap = input('Type "1" to run through, type "2" to walk carfully. ')
        if trap == '1' :
            print('There wasnt any Traps Hooray, or so u thought. ')
            print('there was indeed no traps but there were monster sleeping around and heard you running and came for you and killed u. ')
            print('')
            print('You Lost :)')
    else : 
        print('now that u have chosen ur path u have to make one more decision!. ')
        print('')
        print('u have 2 options: ')
        print('1- run through the road so if there was a trap  wont get cought in it. ')
        print('2- walk carfully but then the trap might be fast and kill you befor u can even react. ')
        print('')
        trap = input('Type "1" to run through, type "2" to walk carfully. ')
        print('')
        if trap == '1' :
             print('There wasnt any Traps Hooray, or so u thought. ')
             print('there was indeed no traps but there were monster sleeping around and heard you running and came for you and killed u. ')
             print('')            
             print('You Lost :)')
        else :
          print('u walked carfully even when u knew that u might not be fast enough to react to the trap ')
          print('never the less that was the right choice. ')
          print('because there were mosnters sleeping in the shadows and in u didnt wake them up. ')
          print('Congratulations, u have succesfully left the dungeon without any injury. ')
          print('')
          print('You won 💝')
          print('..... (¯`v´¯)♥')
          print('.......•.¸.•´')
          print('....¸.•´')
          print('...')
          print(' ☻/')
          print('/▌♥♥')
          print('/ \ ♥♥')

if machiengun == "room": 
    print('u did get in the treasure room but the leader is still persuing u like there is no tomorrow! ')
    print('in the mysterious treasure room, and u find a weird fruit! ')
    print('and under the mysterious fruit there is an explanation written in ancient langauge , and it says: ')
    print('this fruit can give u special powers!, but ofcours there is a catch ')
    print('this fruit can give u powers but also can kill you! ')
    print('u can take 1 bite from it, take 2 bites or take 3 bites one can give u powers and the rest can kill you! choose wisly ')
    fruit = int(input('How many bites do u want to take? '))
    if fruit >= 3 :
        print('u died')
    if fruit >= 2 : 
        print('u died')
    if fruit <= 1 : 
        print('u gained the power, and killed the mosnter king!')
        print('')
        print('u have won, congratulations:D')
